// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRQ5IeSsTxHa1XEHSbaeESh69fwWGemE',
    appId: '1:359591953922:android:012db14820f7c5f9fe891b',
    messagingSenderId: '359591953922',
    projectId: 'moviez-22d87',
    storageBucket: 'moviez-22d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qpzXCY2JbNLX1ulAD6M902zfVVqcRCQ',
    appId: '1:359591953922:ios:8207cac1cf27aae8fe891b',
    messagingSenderId: '359591953922',
    projectId: 'moviez-22d87',
    storageBucket: 'moviez-22d87.firebasestorage.app',
    iosBundleId: 'com.example.moviez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9qpzXCY2JbNLX1ulAD6M902zfVVqcRCQ',
    appId: '1:359591953922:ios:8207cac1cf27aae8fe891b',
    messagingSenderId: '359591953922',
    projectId: 'moviez-22d87',
    storageBucket: 'moviez-22d87.firebasestorage.app',
    iosBundleId: 'com.example.moviez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqiZ7IHR9A3RTOleuydr5KaoZMqxrvtj4',
    appId: '1:359591953922:web:cd11eb59eb435051fe891b',
    messagingSenderId: '359591953922',
    projectId: 'moviez-22d87',
    authDomain: 'moviez-22d87.firebaseapp.com',
    storageBucket: 'moviez-22d87.firebasestorage.app',
    measurementId: 'G-39VWMPZT9E',
  );
}
